Implement component for e-shop
st-canpham/FE-React_Pham-Thanh-Can_STI0060 pull request #1
Opened 2022-06-30 10:25 UTC by st-canpham

#### References
- [Design](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=8%3A194)
#### Description
- Implement component for e-shop page
#### Screenshots
![screencapture-localhost-3000-2022-06-30-17_23_44](https://user-images.githubusercontent.com/106951680/176654964-62ffdaee-9711-4e35-8ec0-0715369cffea.png)

#### Checklist
- [ ] Code đã được build và test ở môi trường local.
- [ ] Tất cả những lỗi cơ bản đã được tìm thấy và sửa chữa

2022-06-30 15:59 UTC, st-quangnguyen2 requested changes
@st-canpham check cmt

2022-06-30 15:59 UTC, st-quangnguyen2 commented on e-shop/src/app/shared/components/layout/Footer.tsx
> +function Footer() {
không dùng thẳng `svg`, viết `function` `render` ra các nội dung tương tự nhau trong `ul`

2022-06-30 15:59 UTC, st-quangnguyen2 commented on e-shop/src/app/assets/icons/index.ts
> +export default Icon;
check hết tất cả các file , add new line EOF

2022-06-30 15:59 UTC, st-quangnguyen2 commented on e-shop/src/app/pages/home/Home.tsx
> +const Home = () => {
- `file` này em đổi tên thành `index.tsx` trong `folder` `home` em thêm một `folder` tên là `components` để chứa các `section`. Mỗi `section` một `folder` trong có có `index.tsx` và các `file` `component` riêng của `section`.
- không dùng thẳng `svg`
- viết `function` để `render` list content tương tự nhau

2022-07-01 06:52 UTC, st-duynguyen approved these changes
@st-canpham will continue fix comments in next PR

2022-07-01 06:52 UTC, merged